### ISSUE TITLE
Create wireframes

### ISSUE THREAD

**Issue by aslinedvinsson** [aslinedvinsson/Axisofaccesshack#2]
Ashley is taking over the job of wireframes as we need them asap. Tamanna is of course very welcome to help Ashley when you are available, otherwise we find something else you can do:)

**Comment by AshLaw96** [comment]
# Wireframes

### Home page
![screenshot](https://github.com/user-attachments/assets/ffb3a755-9289-4a08-89ef-e1240c1d730d)

### Sign-up page
![screenshot](https://github.com/user-attachments/assets/1cdb5fa4-d097-4145-a959-719268b0e34c)

### Carer profile page
![screenshot](https://github.com/user-attachments/assets/a8000df5-ebf3-40ac-b855-299744549604)

### Client profile page
![screenshot](https://github.com/user-attachments/assets/1d89fac2-c66d-4d9e-979f-408226eddd65)
