### ISSUE TITLE
Styling of Login, Logout and Register forms

### ISSUE THREAD

**Issue by olliesharp5** [aslinedvinsson/Axisofaccesshack#61]
Login form: an allauth form found at: templates - allauth - account - login.html
Logout form: an allauth form found at: templates - allauth - account - logout.html
Register form: a custom template found in the accounts APP - templates - register.html

consider using crispy forms?

**Comment by aslinedvinsson** [comment]
And maybe use another word than "Enduser". It might be hard to understand. I can't come up with the ideal word but maybe something like "person using IconicNeeds" or just "user"
